const Countries = {
  Afghanistan: 'Afghanistan',
  Albania: 'Albania',
  Algeria: 'Algeria',
  Andorra: 'Andorra',
  Angola: 'Angola',
  AntiguaAndBarbuda: 'Antigua and Barbuda',
  Argentina: 'Argentina',
  Armenia: 'Armenia',
  Australia: 'Australia',
  Austria: 'Austria',
  Azerbaijan: 'Azerbaijan',
  Bahamas: 'Bahamas',
  Bahrain: 'Bahrain',
  Bangladesh: 'Bangladesh',
  Barbados: 'Barbados',
  Belarus: 'Belarus',
  Belgium: 'Belgium',
  Belize: 'Belize',
  Benin: 'Benin',
  Bhutan: 'Bhutan',
  Bolivia: 'Bolivia',
  BosniaAndHerzegovina: 'Bosnia and Herzegovina',
  Botswana: 'Botswana',
  Brazil: 'Brazil',
  Brunei: 'Brunei',
  Bulgaria: 'Bulgaria',
  BurkinaFaso: 'Burkina Faso',
  Burundi: 'Burundi',
  Cambodia: 'Cambodia',
  Cameroon: 'Cameroon',
  Canada: 'Canada',
  Chad: 'Chad',
  Chile: 'Chile',
  China: 'China',
  Colombia: 'Colombia',
  Croatia: 'Croatia',
  Cuba: 'Cuba',
  Cyprus: 'Cyprus',
  Czechia: 'Czechia',
  Denmark: 'Denmark',
  DominicanRepublic: 'Dominican Republic',
  Ecuador: 'Ecuador',
  Egypt: 'Egypt',
  ElSalvador: 'El Salvador',
  Estonia: 'Estonia',
  Ethiopia: 'Ethiopia',
  Fiji: 'Fiji',
  Finland: 'Finland',
  France: 'France',
  Georgia: 'Georgia',
  Germany: 'Germany',
  Greece: 'Greece',
  Guatemala: 'Guatemala',
  Haiti: 'Haiti',
  Honduras: 'Honduras',
  Hungary: 'Hungary',
  Iceland: 'Iceland',
  India: 'India',
  Indonesia: 'Indonesia',
  Iran: 'Iran',
  Iraq: 'Iraq',
  Ireland: 'Ireland',
  Israel: 'Israel',
  Italy: 'Italy',
  Jamaica: 'Jamaica',
  Japan: 'Japan',
  Kazakhstan: 'Kazakhstan',
  Kenya: 'Kenya',
  Latvia: 'Latvia',
  Lebanon: 'Lebanon',
  Lithuania: 'Lithuania',
  Luxembourg: 'Luxembourg',
  Madagascar: 'Madagascar',
  Malaysia: 'Malaysia',
  Mexico: 'Mexico',
  Moldova: 'Moldova',
  Monaco: 'Monaco',
  Mongolia: 'Mongolia',
  Montenegro: 'Montenegro',
  Morocco: 'Morocco',
  Myanmar: 'Myanmar',
  Namibia: 'Namibia',
  Nepal: 'Nepal',
  Netherlands: 'Netherlands',
  NewZealand: 'New Zealand',
  Nicaragua: 'Nicaragua',
  Nigeria: 'Nigeria',
  NorthMacedonia: 'North Macedonia',
  Norway: 'Norway',
  Pakistan: 'Pakistan',
  Panama: 'Panama',
  Paraguay: 'Paraguay',
  Peru: 'Peru',
  Philippines: 'Philippines',
  Poland: 'Poland',
  Portugal: 'Portugal',
  Qatar: 'Qatar',
  Romania: 'Romania',
  Russia: 'Russia',
  Rwanda: 'Rwanda',
  SaudiArabia: 'Saudi Arabia',
  Serbia: 'Serbia',
  Singapore: 'Singapore',
  Slovakia: 'Slovakia',
  Slovenia: 'Slovenia',
  SouthAfrica: 'South Africa',
  SouthKorea: 'South Korea',
  Spain: 'Spain',
  SriLanka: 'Sri Lanka',
  Sudan: 'Sudan',
  Sweden: 'Sweden',
  Switzerland: 'Switzerland',
  Syria: 'Syria',
  Thailand: 'Thailand',
  Tunisia: 'Tunisia',
  Turkey: 'Turkey',
  Uganda: 'Uganda',
  Ukraine: 'Ukraine',
  UnitedArabEmirates: 'United Arab Emirates',
  UnitedKingdom: 'United Kingdom',
  UnitedStates: 'United States',
  Uruguay: 'Uruguay',
  Venezuela: 'Venezuela',
  Vietnam: 'Vietnam',
  Yemen: 'Yemen',
  Zambia: 'Zambia',
  Zimbabwe: 'Zimbabwe',
};

module.exports = { Countries };

